### ISSUE TITLE
Feature: add support for OpenAsSecondary

### ISSUE THREAD

**Issue by ofek** [xyb/rocksdb3#1]
Doc: https://github.com/facebook/rocksdb/wiki/Secondary-instance
Code: https://github.com/facebook/rocksdb/blob/v6.22.1/include/rocksdb/db.h#L192-L215

**Comment by xyb** [comment]
@ofek sorry for the delayed reply. I haven't had enough time to do this recently, maybe I can try to implement it in 1 or 2 months. But your contribution is always welcome.

**Comment by xyb** [comment]
@ofek Hi, I have added support for secondary instance. But the Github Actions to release the binaries for version 0.0.3 has failed, and I may fix it later. You might want to build python wheels yourself if you want to use this soon.

**Comment by ofek** [comment]
Thanks!!!

**Comment by xyb** [comment]
@ofek binaries released, please install https://pypi.org/project/rocksdb3/0.0.4/

**Comment by ofek** [comment]
Awesome work, thank you 🙇
